### PR TITLE
More than one drive requirement -> core

### PR DESCRIPTION
**Pull request by hillelv**

### CODE REVIEW

**Review by bossyshrimp68 — APPROVED** [review]

**Review by YHerm — APPROVED** [review]

**Review by YHerm — CHANGES_REQUESTED** [review]
It needs at least simulation tests

**Review by YHerm — APPROVED** [review]

**Review by GilStein1 — APPROVED** [review]

**Review by YoniKiriaty — APPROVED** [review]

**Review by GilStein1 — APPROVED** [review]
Very good👌

**Review by drorta — APPROVED** [review]
Ran :)

**Review by YHerm — APPROVED** [review]
Make sure it’s tested!

**Pull request merged**
