### PR TITLE
Never wrap function name to next line

### PR DESCRIPTION
**Pull request by emilyyyylime**

### CODE REVIEW

**Review by YHerm — DISMISSED** [review]

**Comment by hillelv** [comment]
Is this all the places in the code where formatter is turned off for this reason?

**Comment by YHerm** [comment]
> Is this all the places in the code where formatter is turned off for this reason?

yes

**Comment by hillelv** [comment]
> yes

Then why are you fixing this small bug instead of the more common ones😭😭

**Review by hillelv — APPROVED** [review]

**Comment by emilyyyylime** [comment]
Actually in core `@formatter:off` is only used 3 times

And one of those times is the pigeon

**Comment by emilyyyylime** [comment]
If you know of any other specific reproducible formatter bugs please let me know!

**Comment by hillelv** [comment]
> Actually in core `@formatter:off` is only used 3 times
In core there are only utils and hardware, in branches like swerve or pose estimator it's more common

**Review by Yotam7 — DISMISSED** [review]

**Review by bossyshrimp68 — APPROVED** [review]

**Comment by Sh-Pe** [comment]
> Actually in core `@formatter:off` is only used 3 times
> 
> And one of those times is the pigeon

It's twice as much in the poseestimator branches

**Review by Sh-Pe — APPROVED** [review]

**Review by YHerm — APPROVED** [review]

**Pull request merged**
